
package co.com.service.consumer.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.2
 * Sat May 05 12:33:10 COT 2018
 * Generated source version: 2.4.2
 */

@XmlRootElement(name = "greetingWithNameResponse", namespace = "http://consumer.service.com.co/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "greetingWithNameResponse", namespace = "http://consumer.service.com.co/")

public class GreetingWithNameResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

