
package co.com.service.consumer.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.2
 * Sat May 05 12:33:10 COT 2018
 * Generated source version: 2.4.2
 */

@XmlRootElement(name = "greetingWithName", namespace = "http://consumer.service.com.co/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "greetingWithName", namespace = "http://consumer.service.com.co/")

public class GreetingWithName {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

